### ISSUE TITLE
[Crash]: Latest Update Causing Crash on Boot

### ISSUE THREAD

**Issue by Camawama** [Fuzss/diagonalfences#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.1

### Notes (Required)

This might be caused by a mod conflict in my pack but it wasn't an issue until the recent update.

1. Update either Diagonal Fences or Diagonal Windows
2. Boot up game
3. Witness crash

### Crash Report (Required)

https://gist.github.com/Camawama/cc1db7c9674bb0c99494cd9ad33a284b

### latest.log (Optional)

https://gist.github.com/Camawama/a0c1bec9991bd163426449c28f0f2d68

**Comment by Fuzss** [comment]
This is your issue. Please report it to the Forgified Fabric Api. The faulty class is usually only used during development, but the diagonal blocks mods load it during production. So the issue probably has gone unnoticed so far.

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector registerBlockStateModels(Lnet/minecraft/data/models/BlockModelGenerators;)V in fabric-data-generation-api-v1.mixins.json:ModelProviderMixin from mod fabric_data_generation_api_v1 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-data-generation-api-v1-refmap.json`

**Comment by Fuzss** [comment]
I've now made sure in more recent versions of Puzzles Lib that the problematic class is no longer accessed. So the game will work, but the conflict FFAPI is having is not fixed.
