### ISSUE TITLE
[Bug]: Latest Version Breaks all Fences and They Must be Replaced.

### ISSUE THREAD

**Issue by WildFyr16** [Fuzss/diagonalfences#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.2

### Notes (Required)

All fences are not connected and must be replaced down to connect again

**Comment by Fuzss** [comment]
Yes, that’s unfortunately intentional. Diagonal Fences are now separate blocks. When updating I recommend using the `/fill` command to convert fences. You can use it to e.g. replace `minecraft:oak_fence` with `diagonalfences:minecraft/oak_fence` in an area and the diagonal connections will come back.
